### ISSUE TITLE
docs: custom numbered headings synced with contents lists

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern-com-website#324] opened 2020-12-07 09:45 UTC
### What

A proposal for custom numbered headings in docs that reflect in contents lists at tops of doc pages.

This info design strategy is used a lot in lengthier technical documentation (and grey literature, etc), which is what Txp docs are somewhat heading toward with their new holistic goal-oriented development (e.g. the themes doc). 

Such numbering on headings, synced with contents lists, provide clear visual indication of the conceptual order document topics are structured, as well helps to keep readers oriented as they get deeper into longer doc pages.

### Example

You can see an example of what I'm talking about on my policies page, https://wion.com/policies, and look at the CSS. I think it's nice to add the leading zero on single-digit numbers so they are all aligned as double-digits in the contents lists.

From my CSS:

```
/* Contents list 'item' ordering, two levels */
.toc1, .toc2 {list-style: none;}
.toc1 {counter-reset: item -1; padding-left: 0;}
.toc1 li {counter-increment: item;}
.toc1 li::before {content: counter(item, decimal-leading-zero) ' ';}
.toc2 {counter-reset: item;}
.toc2 li::before {content: counters(item, '.') ' ';}

/* Page 'section' (h2) and 'subsection' (h3) ordering in sync with contents list */
.a3 {counter-reset: section -1;}
.a3 h2 {counter-reset: subsection;}
.a3 h2::before {counter-increment: section; content: counter(section, decimal-leading-zero) ' ';}
.a3 h3::before {counter-increment: subsection; content: counter(section) "." counter(subsection) ' ';}
```

My numbering in the policies page only goes to second-level headings: We would need to go to `h5` headings, at least, in docs. The _docs guidelines_ doc is one example of headings going to `h4`, at least, and maybe themes doc too.

Though we do have a guideline to try and keep docs no deeper than `h4`, that's not always possible, so we might want to play it safe and allow for `h5`, too, if not all the way through `h6`. Numbering also makes deeper headings like this (which tend to be smaller font sizes vs. higher levels) easier to recognize as actual headings versus just bold text.

I'm not sure why I used a class called 'a3' but, you know, use what you like. ;)

Whether or not you wanted these on tag pages, I can't guess, though it wouldn't hurt anything, but you could probably exempt that directory somehow so the numbering didn't show on those pages.

**Comment by philwareham** [comment] 2020-12-09 16:22
Will investigate. Stay tuned.

**Comment by philwareham** [comment] 2020-12-09 17:52
@wion I have coded headings `h2` through to `h4`. Please refresh a docs page such as https://docs.textpattern.com/tags/article and you should see it in situ.

If you are happy this works as intended, I will bullet-proof it by then adding `h5` and `h6` as requested.

**Comment by wion** [comment] 2020-12-09 18:04
I personally like having the numbers.

After looking at it in context. Maybe the leading zero is not necessary (a little too busy?). I'd be happy to relent there according to popular opinion.

Also wondering if it's worth toning down the number colour so it doesn't stand out quite as much as the heading text itself. Or is that even possible? Not a big deal, though.

**Comment by philwareham** [comment] 2020-12-09 18:07
Sure, the leading zero is easy to remove. Styling of the counters is not a problem either, it's just a couple of lines of CSS.

Maybe live with it a day and come back to me with all/any changes you think it needs?

**Comment by wion** [comment] 2020-12-09 18:10
Will do.

**Comment by wion** [comment] 2020-12-10 09:07
Your latest tweaks look good. Only one thing more needed, I think...

On the first level items. Instead of 1, 2, 3, etc, have 1.0, 2.0, 3.0, etc.

Don't know if that's possible, though.

**Comment by philwareham** [comment] 2020-12-10 09:10
> On the first level items. Instead of 1, 2, 3, etc, have 1.0, 2.0, 3.0, etc.

I'm not overly keen on that, it's inconsistent with the subsections (i.e., wouldn't subsection 1 need to be `1.1.0` in that case?).

**Comment by wion** [comment] 2020-12-10 09:12
Yeah, I was just realizing that. Call it good as is!

**Comment by wion** [comment] 2020-12-10 09:13
You may close this if you desire. I'm happy.

**Comment by philwareham** [comment] 2020-12-10 09:13
Cool. Closing now.

**Closed by philwareham** 2020-12-10 09:13 UTC

**Comment by wion** [comment] 2020-12-10 09:14
Oh, there is the deeper levels, though. But I presume you'll get to that. See bullets on some pages mixed with numbers.

**Comment by philwareham** [comment] 2020-12-10 09:16
I broke the 2nd subsection - should be fixed if you refresh browser. Will do `h5` and `h6` levels in due course.

**Comment by wion** [comment] 2020-12-10 09:17
I refreshed but see third-level bullets, eg: https://docs.textpattern.com/brand/user-docs-collaboration

**Comment by wion** [comment] 2020-12-10 09:18
Maybe it's my cache.

**Comment by philwareham** [comment] 2020-12-10 09:19
Probably - looks fine to me. Use option + command + r on macOS to force cache refresh.

**Comment by wion** [comment] 2020-12-10 09:20
Good. See it now.

**Comment by wion** [comment] 2020-12-10 09:25
Well, I see it in Safari, but not FF.  Do you mean Alt+Command+r? That just changes my screen to reader view (which I didn't know, and is nice).

But if you did browser testing, I'm happy to take your word for it. FF will probably shape up for me eventually.

**Comment by philwareham** [comment] 2020-12-10 09:33
Annoying it is `command` + `shift` +  r` to force refresh in Firefox on macOS. I accidentally invoke the reader view there all the time (as I primarily develop using Safari's dev tools).

**Comment by philwareham** [comment] 2020-12-10 09:34
FYI I've also done the `h5` and `h6` levels now. So hopefully it should be fairly bullet-proof.

**Comment by wion** [comment] 2020-12-10 09:35
Bingo. Thanks, Phil!
